### ISSUE TITLE
How do we make OFPlugin part of the core?

### ISSUE THREAD

**Issue by reginaflores** [openframeworks/OFXcodeMenu#37]
With whom do we need to speak to make this happen.... this function is pretty critical to workflow and I think it should be included in the core... thoughts?

**Comment by admsyn** [comment]
Hi @reginaflores, this was brought up way back when OFPlugin was announced on the dev list. At the time we weren't really sure if people would find it useful, and if it'd even survive beyond the next Xcode version.

It might be a decent time to bring it up again, though! Either an issue on the OF github repo or a dev mailing list post would probably be the right venue.

**Comment by reginaflores** [comment]
Thanks!
> On Jul 23, 2015, at 3:34 PM, Adam Carlucci <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> Hi @reginaflores <https://github.com/reginaflores>, this was brought up way back when OFPlugin was announced on the dev list. At the time we weren't really sure if people would find it useful, and if it'd even survive beyond the next Xcode version.
> 
> It might be a decent time to bring it up again, though! Either an issue on the OF github repo or a dev mailing list post would probably be the right venue.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/admsyn/OFPlugin/issues/37#issuecomment-124219377>.
> 

Regina Flores Mir
MFA Design and Technology Candidate | Parsons School of Design
regina.flores@newschool.edu <mailto:regina.flores@newschool.edu>    |  reginafloresmir.com <http://reginafloresmir.com/>

**Comment by admsyn** [comment]
Going to close this, as it's been moved over to the OF organization now. Thanks for the push @reginaflores !

**Comment by reginaflores** [comment]
Thank you! I have everyone at Parsons DT using your add-on! We all love it! Thank you for making it!
