### ISSUE TITLE
ofxOsc (and similarly structured addons -- no include dir) fail to compile w/o adding src to header search paths.

### ISSUE THREAD

**Issue by bakercp** [openframeworks/OFXcodeMenu#38]
Hey there ... maybe I'm doing it wrong, but for whatever reason when I add ofxOsc via OFPlugin, compilation fails because the oscpack headers (which, unfortunately are in its `src` folder) are not in the header search paths.  I'm not sure what the solution is (other than conditionally add the `src` folder if no 3rd party `include` folder is found).  Anyway, again, maybe I'm using it wrong, but if not, I wanted to note that here.  Thanks for all of your work on this supertool @admsyn.

**Comment by admsyn** [comment]
Hey @bakercp, yeah ofxOsc is a bit of a confounding case for OFPlugin's header path logic. I haven't really had the heart to change the logic to "add all paths as include paths", but maybe that's the right way to go (or maybe just as a special case for ofxOsc). 

Related #28 openframeworks/openframeworks#3575 #27

**Comment by bakercp** [comment]
Oops, should have searched closed issues :) yeah not sure what the best to do it is. As a core add-on, an exception may be justified.
