### ISSUE TITLE
Needs Xcode 7.2 UUID

### ISSUE THREAD

**Issue by admsyn** [openframeworks/OFXcodeMenu#42]

**Comment by dimitre** [comment]
maybe copy from here? https://github.com/travisjeffery/ClangFormat-Xcode/blob/master/ClangFormat/ClangFormat-Info.plist

**Comment by admsyn** [comment]
yeah it's pretty easy to get, see the README :) just reminding myself to do it later today

**Comment by admsyn** [comment]
I'd accept a PR if you have a moment, though!

**Comment by admsyn** [comment]
closed by #43
