### ISSUE TITLE
can't see OF menu with Xcode Version 8.2.1 (8C1002)

### ISSUE THREAD

**Issue by batchku** [openframeworks/OFXcodeMenu#49]
Hello!

I love and have been using this addon for years now :)

I am having trouble getting it to work with Xcode 8.2.1.  I followed the troubleshooting instructions and added the DVTPlugInCompatibilityUUIDs for my xcode version and rebuilt the plugin.  

I have verified that the plugin is in fact here:
```
~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OFXcodeMenu.xcplugin
```

What else can I check?

**Comment by bakercp** [comment]
See https://github.com/openframeworks/OFXcodeMenu/issues/48 and https://github.com/openframeworks/OFXcodeMenu/issues/46
