### ISSUE TITLE
support of XCode 8+

### ISSUE THREAD

**Issue by tremblap** [openframeworks/OFXcodeMenu#50]
Hello

Thanks for your hard work - I can see no new version support the new XCode. I sadly have a new machine and I'm stuck with the latest XCode and UUID hack proposed does not add a menu item.

Is there an update on the way?

thanks

**Comment by admsyn** [comment]
No, sorry, it's not really possible with Xcode 8 since they revamped the plugin API, see https://github.com/openframeworks/OFXcodeMenu/issues/46
